sudo: required

language: node_js

node_js:
  - "4.4"

services:
  - docker

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - npm run dist
  - docker build -t macacomaluco/macaco-maluco:latest .

after_success:
  - test $TRAVIS_BRANCH == "master" && docker push macacomaluco/macaco-maluco:latest
